Repository mozilla/fxa-customs-server, pull requests merged in 2018-03, with the labels that each got.

#230 fix(test): #228 Start memcached as part of 'npm test'
  README.md
  scripts/test-local.sh
  test/memcache-helper.js
Labels: waffle:backlog

#231 chore(deps): update ip-reputation-js-client
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#232 fix(node): Use Node.js v6.14.0
  Dockerfile-build
Labels: waffle:active
