Repository mozilla/fxa-customs-server, pull requests merged in 2018-10, with the labels that each got.

#281 chore(release): Merge train-122 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#282 chore(release): Merge train-123 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#280 fix(deps): add filtered npm audit support
  .nsprc
  .travis.yml
  npm-shrinkwrap.json
  package.json
Labels: train-124, waffle:review

#283 feat(deps): Add tls-shrink, remove "^" prefix on audit-filter version
  npm-shrinkwrap.json
  package.json
  scripts/tls-shrink.sh
Labels: shipit, train-124, waffle:review

#284 chore(release): Merge train-124 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active
