Repository mozilla/fxa-customs-server, pull requests merged in 2018-06, with the labels that each got.

#255 fix(docker): base image node:8-alpine and upgrade to npm6
  Dockerfile-build
Labels: waffle:active

#254 merge train-114 into master
  CHANGELOG.md
  Dockerfile-build
  npm-shrinkwrap.json
  package.json
  scripts/test-local.sh
Labels: waffle:review

#256 Merge v1.114.3 to master
  CHANGELOG.md
  README.md
  lib/actions.js
  npm-shrinkwrap.json
  package.json
  test/remote/too_many_verify_codes.js
Labels: waffle:active

#251 Updates to reputation service integration
  lib/reputationService.js
  npm-shrinkwrap.json
  package.json
  test/remote/check_reputation_tests.js
  test/test_reputation_server_stub.js
Labels: waffle:review

#253 test(reputation): adds compose based integration test with iprepd
  test/integration/reputation/README.md
  test/integration/reputation/docker-compose.yml
  test/integration/reputation/iprepd.yaml
  test/integration/reputation/iprepd_tests.js
  test/memcache-helper.js
Labels: waffle:backlog

#257 Release v1.115.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active
